language: cpp
sudo: required
dist: trusty
compiler:
  - clang
  - gcc
install:
  - if [ "$CXX" = "g++" ]; then g++ -v; else clang -v; fi

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - clang
      - libmysqlclient18
      - qtbase5-dev
      - qttools5-dev
      - qttools5-dev-tools
      - libqt5sql5-mysql 

script: ./travis.sh 

branches:
  except:
    - appveyor
