version: "{branch}-ci-{build}"
os:
- Visual Studio 2013

platform:
- Win32

configuration:
- Debug 
- Release

on_finish:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

environment:
  QTDIR: C:\Qt\5.5\msvc2013 
  MYSQL_INCLUDEDIR: C:\Librart
  MYSQL_LIBRARYDIR: C:\Program Files\MySQL\MySQL Server 5.6\lib

install:
#- git submodule init
#- git submodule update
- set PATH=%PATH%;%QTDIR%\bin
- qmake -v

build_script:
- qmake
- nmake

test_script:

notifications:
- provider: Email
  to:
    - konserw@gmail.com
  subject: kOferta AppVeyor Build
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
